// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuRqnLMxu-Q32fhcfIGD7XtpPWwqS-rpU',
    appId: '1:269806852648:web:b97cdc94478b1311d9731d',
    messagingSenderId: '269806852648',
    projectId: 'ves-hackit',
    authDomain: 'ves-hackit.firebaseapp.com',
    storageBucket: 'ves-hackit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxl5ZEGtZ_R860OW9oftuYCM46G6GMEr0',
    appId: '1:269806852648:android:c7ae750ed29cd875d9731d',
    messagingSenderId: '269806852648',
    projectId: 'ves-hackit',
    storageBucket: 'ves-hackit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR9vm9kD65KKW0LEiMqmm81vsYzLdFkq4',
    appId: '1:269806852648:ios:08264555459c4001d9731d',
    messagingSenderId: '269806852648',
    projectId: 'ves-hackit',
    storageBucket: 'ves-hackit.firebasestorage.app',
    iosBundleId: 'com.ishan.foodon',
  );
}
